package com.lpdev.salesmanagement.entities;
// Generated Sep 15, 2019 11:38:00 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "sales_management")
public class Category implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private String note;
	private Long created;
	private Long updated;
	private Set<PropertyValue> propertyValues = new HashSet<PropertyValue>(0);
	private Set<Category> categories = new HashSet<Category>(0);
	private Set<Product> products = new HashSet<Product>(0);

	public Category() {
	}

	public Category(Category category, String name, String note, Long created, Long updated,
			Set<PropertyValue> propertyValues, Set<Category> categories, Set<Product> products) {
		this.category = category;
		this.name = name;
		this.note = note;
		this.created = created;
		this.updated = updated;
		this.propertyValues = propertyValues;
		this.categories = categories;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "created")
	public Long getCreated() {
		return this.created;
	}

	public void setCreated(Long created) {
		this.created = created;
	}

	@Column(name = "updated")
	public Long getUpdated() {
		return this.updated;
	}

	public void setUpdated(Long updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	@JsonIgnore
	public Set<PropertyValue> getPropertyValues() {
		return this.propertyValues;
	}

	public void setPropertyValues(Set<PropertyValue> propertyValues) {
		this.propertyValues = propertyValues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	@JsonIgnore
	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	@JsonIgnore
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
