package com.lpdev.salesmanagement.entities;
// Generated Sep 15, 2019 11:38:00 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductDetailId generated by hbm2java
 */
@Embeddable
public class ProductDetailId implements java.io.Serializable {

	private int productId;
	private int propertyValueId;

	public ProductDetailId() {
	}

	public ProductDetailId(int productId, int propertyValueId) {
		this.productId = productId;
		this.propertyValueId = propertyValueId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "property_value_id", nullable = false)
	public int getPropertyValueId() {
		return this.propertyValueId;
	}

	public void setPropertyValueId(int propertyValueId) {
		this.propertyValueId = propertyValueId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductDetailId))
			return false;
		ProductDetailId castOther = (ProductDetailId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getPropertyValueId() == castOther.getPropertyValueId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getPropertyValueId();
		return result;
	}

}
