package com.lpdev.salesmanagement.entities;
// Generated Sep 15, 2019 11:38:00 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductDetail generated by hbm2java
 */
@Entity
@Table(name = "product_detail", catalog = "sales_management")
public class ProductDetail implements java.io.Serializable {

	private ProductDetailId id;
	private Product product;
	private PropertyValue propertyValue;
	private String note;
	private Long created;
	private Long updated;

	public ProductDetail() {
	}

	public ProductDetail(ProductDetailId id, Product product, PropertyValue propertyValue) {
		this.id = id;
		this.product = product;
		this.propertyValue = propertyValue;
	}

	public ProductDetail(ProductDetailId id, Product product, PropertyValue propertyValue, String note, Long created,
			Long updated) {
		this.id = id;
		this.product = product;
		this.propertyValue = propertyValue;
		this.note = note;
		this.created = created;
		this.updated = updated;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "propertyValueId", column = @Column(name = "property_value_id", nullable = false)) })
	public ProductDetailId getId() {
		return this.id;
	}

	public void setId(ProductDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "property_value_id", nullable = false, insertable = false, updatable = false)
	public PropertyValue getPropertyValue() {
		return this.propertyValue;
	}

	public void setPropertyValue(PropertyValue propertyValue) {
		this.propertyValue = propertyValue;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "created")
	public Long getCreated() {
		return this.created;
	}

	public void setCreated(Long created) {
		this.created = created;
	}

	@Column(name = "updated")
	public Long getUpdated() {
		return this.updated;
	}

	public void setUpdated(Long updated) {
		this.updated = updated;
	}

}
