package com.lpdev.salesmanagement.entities;
// Generated Sep 15, 2019 11:38:00 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name = "property", catalog = "sales_management")
@Proxy(lazy = false)
public class Property implements java.io.Serializable {

	private String code;
	private String name;
	private String note;
	private Long created;
	private Long updated;
	private Set<PropertyValue> propertyValues = new HashSet<PropertyValue>(0);

	public Property() {
	}

	public Property(String code) {
		this.code = code;
	}

	public Property(String code, String name, String note, Long created, Long updated,
			Set<PropertyValue> propertyValues) {
		this.code = code;
		this.name = name;
		this.note = note;
		this.created = created;
		this.updated = updated;
		this.propertyValues = propertyValues;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "created")
	public Long getCreated() {
		return this.created;
	}

	public void setCreated(Long created) {
		this.created = created;
	}

	@Column(name = "updated")
	public Long getUpdated() {
		return this.updated;
	}

	public void setUpdated(Long updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "property")
	@JsonIgnore
	public Set<PropertyValue> getPropertyValues() {
		return this.propertyValues;
	}

	public void setPropertyValues(Set<PropertyValue> propertyValues) {
		this.propertyValues = propertyValues;
	}

}
